### ISSUE TITLE
Shuffle the cards in the deck

### ISSUE THREAD

**Issue by padalah** [cs361fall2017/team23#2]

**Comment by dhanensm** [comment]
**Card:** As a player of Aces Up, I want the deck to be shuffled so that the game is fair.

**Conversation:**
* Know length of deck
* Randomly generate a location and swap for every element in deck
* Make sure random numbers do not exceed the size of the deck

**Confirmation:**
* At the start of the game, cards will be displayed on the screen.
* Restart the game and make sure the original cards dealt are not the same as the previous run.
* When the user chooses to add four new cards throughout the game, they should not be in order.

Estimated time: 1 hour

**Comment by padalah** [comment]
#9
