### ISSUE TITLE
Move a card from 1 column to another

### ISSUE THREAD

**Issue by padalah** [cs361fall2017/team23#5]

**Comment by ErinTanaka** [comment]
Mine!!! Question: How do I actually check if the column is empty?

**Comment by ErinTanaka** [comment]
Card: As a player of Aces Up, I want to be able to move a card from one of the four columns to an empty one in order to either free up a card for removal or to get the aces up to the top.

Conversation:

Fields to specify from which column a card is being removed and the column number of where player wants it to go.
Button to confirm/make move happen
The column specified for the card to move to must be empty.
Card in "from" field is removed from that column.
Card removed from "from" field is placed in "to" field iff "to" column is empty.
If there are cards in the "to" column do nothing.
Confirmation:

Enter column number 0-3 to "from" field
Enter column number 0-3 to "to" field
Click "Move" button
if "to" column is empty check that card in "from" column is removed and placed in "to"
if "to" column has cards check that card in "from" column stays in place

Estimated time: 1 hour

**Comment by padalah** [comment]
#4
